// AUTO-GENERATED by scripts/build-character-registry.mjs.
// 직접 편집하지 말 것. 데이터는 ./data/<id>.json 에서 관리하고 빌드 시 자동 갱신된다.

import type { CharacterDef } from "./types";

export const TYPING_CHARACTERS: readonly CharacterDef[] = [
  {
    id: "camel",
    label: {
      ko: "낙타",
      en: "Camel",
    },
    sprite: "/sprites/camel-run.png",
    frameWidth: 96,
    frameHeight: 96,
    frameCount: 6,
    frameCols: 2,
    fps: 10,
  },
  {
    id: "asuna",
    label: {
      ko: "아스나",
      en: "Asuna",
    },
    sprite: "/sprites/characters/asuna/run.png",
    frameWidth: 192,
    frameHeight: 208,
    frameCount: 8,
    frameCols: 8,
    fps: 4,
    credit: {
      source:
        "Yuuki Asuna chibi sprite (사용자 부여 공개 배포 허가, 2026-05-03)",
      license: "approved",
    },
  },
  {
    id: "linnea",
    label: {
      ko: "린네아",
      en: "Linnea",
    },
    sprite: "/sprites/characters/linnea/run.png",
    frameWidth: 192,
    frameHeight: 208,
    frameCount: 8,
    frameCols: 8,
    fps: 4,
    credit: {
      source:
        "Augury Bird fae chibi sprite (사용자 부여 공개 배포 허가, 2026-05-03)",
      license: "approved",
    },
  },
];

export const DEFAULT_CHARACTER_ID = "camel";
