export { GameServiceHome } from "./game-service-home";
export { GameDetail } from "./game-detail";
export {
  CURATED_GAMES,
  GAME_CATALOG,
  GAME_CATEGORIES,
  GAME_CATEGORY_LABELS,
  GAME_CATEGORY_ORDER,
  GAME_COLLECTIONS,
  GAME_COLLECTION_LABELS,
  GAME_HUB_TABS,
  GAME_PROVIDER,
  GAME_REGIONS,
  GAME_REGION_LABELS,
  getCollectionGames,
  getFeaturedGamesForRegion,
  getGameBySlug,
  getGameEmbedKey,
  getGameSlugs,
  getGameTags,
  getListedGames,
  isGameCollection,
  isGameRegion,
  resolveRegionFromCountry,
  type GameCategory,
  type GameCollection,
  type GameEntry,
  type GameHubTab,
  type GameRegion,
} from "./game-catalog";
export {
  GAME_HUB_PAGE_SIZE,
  getDetailGame,
  getGamesBySlugs,
  getHubGames,
  type HubGamesQuery,
  type HubGamesResult,
} from "./game-source";
export {
  getGameServiceText,
  getLanguageDefaultGameRegion,
  getLocalizedGameCategoryLabel,
  getLocalizedGameCollectionLabel,
  getLocalizedGameHubTabs,
  getLocalizedGameRegionLabel,
  getLocalizedGameTags,
  getLocalizedGameText,
  type GameServiceLanguage,
} from "./game-service-i18n";
