spring:
  application:
    name: yeon-backend
  flyway:
    enabled: false
  autoconfigure:
    exclude:
      - org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health

---
spring:
  config:
    activate:
      on-profile: jdbc
