management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health

spring:
  flyway:
    enabled: true
    locations: classpath:db/migration
    default-schema: yeon_backend
    schemas: yeon_backend
