export const CARD_SERVICE_TEXT = {
  state: {
    loading: "불러오는 중...",
    loadingTitle: "로딩",
    bootLoadingMessage: "세션을 확인하고 있습니다.",
    bootLoadingTitle: "카드 서비스 준비 중",
    errorTitle: "오류",
  },
  list: {
    loadingMessage: "불러오는 중...",
    errorMessage: "덱 목록을 불러오지 못했습니다.",
    emptyTitle: "아직 덱이 없습니다",
    emptyMessage: "첫 덱을 만들고 학습할 카드를 추가해보세요.",
    topBarTitle: "카드 덱",
    topBarLogoutLabel: "로그아웃",
    topBarDescriptionGuest:
      "지금 만든 덱은 이 기기에만 저장되며, 로그인하면 계정으로 옮겨 계속 학습할 수 있어요.",
    topBarDescriptionSignedIn:
      "카드를 열어 카드를 추가하고 바로 복습을 시작할 수 있어요.",
    deckSectionTitle: "새 덱 만들기",
    createDeckButtonLabel: "덱 추가",
    creatingDeckLabel: "생성 중...",
    deckNameLabel: "덱 이름",
    deckNamePlaceholder: "예: 면접 질문, 독서 카드",
    loginHintTitle: "로그인하고 동기화하기",
    loginHintDescription: "비회원으로 만든 덱은 이 기기에만 저장됩니다.",
    loginActionLabel: "계정으로 로그인",
    loginBusyLabel: "로그인 중...",
    loginErrorTitle: "로그인 실패",
    loginErrorMessage: "로그인에 실패했습니다.",
    createDeckErrorMessage: "덱 생성에 실패했습니다.",
    loginEmailLabel: "이메일",
    loginEmailPlaceholder: "email@example.com",
    loginPasswordLabel: "비밀번호",
    loginPasswordPlaceholder: "비밀번호",
    cardCountSuffix: "장",
  },
  detail: {
    loadingMessage: "불러오는 중...",
    errorMessage: "카드를 불러오지 못했습니다.",
    emptyTitle: "카드가 없습니다",
    emptyMessage:
      "카드 추가 버튼을 눌러 첫 카드부터 질문과 답변을 작성해보세요.",
    playButtonLabel: "▶ 학습 시작",
    deckTitleFallback: "카드 덱",
    itemLabel: "카드 목록",
    allCardsLabel: "전체",
    sheetCreateLabel: "카드 추가",
    sheetManualLabel: "직접 입력",
    sheetBulkLabel: "AI 형식 붙여넣기",
    sheetTitle: "카드 추가",
    sheetEditTitle: "카드 편집",
    questionLabel: "질문",
    answerLabel: "답변",
    questionHint: "질문을 Markdown으로 입력하세요",
    answerHint: "답변을 Markdown으로 입력하세요",
    submitCreateLabel: "카드 추가",
    submitEditLabel: "수정 저장",
    submitBusyLabel: "추가 중...",
    submitEditBusyLabel: "저장 중...",
    bulkSaveLabel: "미리보기 후 추가",
    bulkHelp:
      "마커가 한 줄 전체가 [[Q]], [[A]], [[CARD]]일 때만 카드로 인식합니다.",
    bulkPlaceholder:
      "[[Q]]\n문제\n[[A]]\n정답\n[[CARD]]\n[[Q]]\n문제\n[[A]]\n정답",
    deleteConfirmTitle: "카드 삭제",
    deleteConfirmMessage: "이 카드를 삭제할까요?",
    deleteConfirmAction: "삭제",
    updateRequiredHint: "질문과 답변을 모두 입력해 주세요.",
    updateErrorMessage: "카드 수정에 실패했습니다.",
    createErrorMessage: "카드 추가에 실패했습니다.",
    deleteErrorMessage: "카드 삭제에 실패했습니다.",
    addErrorMessage: "카드를 불러오지 못했습니다.",
    metaSuffixCreatedAtLabel: "장 · 생성일 ",
    metaCountLabel: "카드",
    modeAuthenticatedLabel: "계정 동기화됨",
    modeGuestLabel: "비회원 모드",
    addCompleteTitle: "추가 완료",
    addCompleteMessageSuffix: "장의 카드를 추가했습니다.",
    cardSettingsTitle: "덱 설정",
    cardSettingsPreparingMessage: "모바일 덱 설정은 준비 중입니다.",
    cardSettingsAccessibilityLabel: "덱 설정",
    addCardActionLabel: "새 카드 추가",
    addCardAccessibilityLabel: "새 카드 추가",
    missingDeckIdMessage: "덱 ID가 없습니다.",
    missingDeckMessage: "덱을 찾을 수 없습니다.",
    noParseResultMessage: "인식할 수 있는 카드가 없습니다.",
    loginRequiredMessage: "로그인이 필요합니다.",
  },
  play: {
    loadingMessage: "불러오는 중...",
    errorMessage: "학습 카드를 불러오지 못했습니다.",
    emptyTitle: "빈 덱",
    emptyMessage: "학습할 카드가 없습니다.",
    titleFallback: "학습",
    headerBackLabel: "← 덱으로",
    homeLabel: "◯",
    studyModeFlashcardLabel: "플래시카드",
    studyModeReviewLabel: "복습 모드",
    reviewModeQuestionLabel: "문제",
    reviewModeAnswerLabel: "정답",
    flipQuestionLabel: "질문",
    flipAnswerLabel: "답변",
    cardMetaSeparator: " / ",
    flipHint: "탭해서 ",
    flipHintPostfix: " 보기",
    reviewHardLabel: "어려움 · 1일 후",
    reviewGoodLabel: "좋음 · 3일 후",
    reviewEasyLabel: "쉬움 · 4일 후",
    reviewSavingLabel: "저장 중...",
    prevLabel: "← 이전",
    nextLabel: "다음 →",
    prevUnavailableMessage: "이전",
    nextUnavailableMessage: "다음",
    modeAuthenticatedLabel: "계정 동기화됨",
    modeGuestLabel: "비회원 모드",
  },
  shared: {
    notFoundMessage: "덱을 찾을 수 없습니다.",
    deleteLabel: "삭제",
    editLabel: "편집",
    closeLabel: "취소",
    inputRequiredTitle: "입력 필요",
    openDeckLabel: "덱 열기",
    openCardLabel: "카드 열기",
    openCardMenuLabel: "카드 메뉴",
    closeModalLabel: "닫기",
    openOptionLabel: "옵션 열기",
    backLabel: "뒤로 가기",
  },
} as const;

export type CardServiceText = typeof CARD_SERVICE_TEXT;
