export const SHARED_FEATURE_CLASS = {
  pageSurface: "min-h-screen bg-white text-[#111]",
  modalOverlay:
    "fixed inset-0 z-50 flex items-center justify-center bg-black/40 px-4",
  modalCard: "w-full max-w-[420px] rounded-xl bg-white p-6",
  text12Emphasis: "text-[12px] font-semibold text-[#111]",
  text12EmphasisMuted: "text-[12px] font-semibold text-[#555]",
  text12EmphasisSubtle: "text-[12px] font-semibold text-[#777]",
  text12EmphasisNeutral: "text-[12px] font-semibold text-[#666]",
  text13Emphasis: "text-[13px] font-semibold text-[#111]",
  text13EmphasisSubtle: "text-[13px] font-semibold text-[#777]",
  text13EmphasisMuted: "text-[13px] font-semibold text-[#666]",
  text13Primary: "text-[13px] text-[#111]",
  text13PrimaryBold: "text-[13px] font-bold text-[#111]",
  text13Secondary: "text-[13px] text-[#6b7280]",
  text13MediumSecondary: "text-[13px] font-medium text-[#666]",
  text15EmphasisOnCream: "text-[15px] font-bold text-[#fffaf4]",
  text13Neutral: "text-[13px] text-[#666]",
  text13Subtle: "text-[13px] text-[#777]",
  text16Secondary: "text-[16px] font-medium text-[#666]",
  text11EmphasisSubtle: "text-[11px] font-semibold text-[#888]",
  text13Soft: "text-[13px] text-[#888]",
  text12Soft: "text-[12px] text-[#888]",
  text16Emphasis: "text-[16px] font-semibold text-[#111]",
  text13PrimaryMedium: "text-[13px] font-medium text-[#111]",
  text14Neutral: "text-[14px] text-[#666]",
  text14Soft: "text-[14px] text-[#888]",
  text14Primary: "text-[14px] text-[#111]",
  text15Primary: "text-[15px] text-[#111]",
  text12Subtle: "text-[12px] text-[#777]",
  text12Neutral: "text-[12px] text-[#666]",
  text22Emphasis: "text-[22px] font-semibold text-[#111]",
  text28Emphasis: "text-[28px] font-semibold text-[#111]",
  text34Emphasis: "text-[34px] font-semibold text-[#111]",
  text12BoldNeutral: "text-[12px] font-bold text-[#666]",
  smallInlineActionButton:
    "inline-flex items-center gap-2 rounded border border-[#e5e5e5] px-5 py-2 text-[13px] font-medium text-[#555] transition-colors hover:border-[#aaa]",
  mutedInputPanel: "rounded-lg border border-[#e5e5e5] bg-[#fafafa] px-3 py-2",
  panelCard: "rounded-2xl border border-[#e5e5e5] bg-white p-4",
  wrapItemsCenterGap2: "flex flex-wrap items-center gap-2",
  inlineItemsCenterGap2: "flex items-center gap-2",
  alignBetweenGap3: "flex items-center justify-between gap-3",
  alignBetweenStartGap3: "flex items-start justify-between gap-3",
  alignBetweenGap3WithMargin3: "mt-3 flex items-center justify-between gap-3",
  alignBetweenGap3WithMargin4: "mt-4 flex items-center justify-between gap-3",
  alignBetweenStartGap3WithMargin4:
    "mb-4 flex items-start justify-between gap-3",
  primaryActionButtonMd14:
    "rounded-xl bg-[#111] px-5 py-3 text-[14px] font-semibold text-white transition-colors hover:bg-[#333]",
  primaryActionButtonMd13:
    "rounded-xl bg-[#111] px-4 py-2 text-[13px] font-semibold text-white transition-colors hover:bg-[#333]",
  headingText22Emphasis: "text-[22px] font-semibold text-[#111]",
  ghostButtonMd14:
    "rounded-xl border border-[#e5e5e5] px-4 py-2 text-[14px] text-[#111] hover:bg-[#fafafa]",
  ghostButtonMd13:
    "rounded-xl border border-[#e5e5e5] px-4 py-2 text-[13px] text-[#111] no-underline transition-colors hover:border-[#111]",
  inputText14:
    "rounded-lg border border-[#e5e5e5] px-3 py-2 text-[14px] text-[#111] outline-none focus:border-[#111]",
  captionMutedMono: "font-mono text-[12px] text-[#aaa]",
  sectionHeading14: "mb-3 text-[14px] font-bold",
  sectionBodyGap3: "mt-3 grid gap-3",
  wrapGap2: "flex flex-wrap gap-2",
  tagPill: "rounded-full border border-[#e5e5e5] px-2 py-0.5",
} as const;
